#!/usr/bin/env python3
# -*- coding: UTF-8 -*- 

import os
import pathlib

print("gen config.ts")

ctxt  = '''
// generated by  compile script
// do not edit it

'''


pwd = os.path.abspath(os.path.dirname(__file__))
print("pwd:",pwd)
plugins = []
p = pathlib.Path(os.path.join(pwd,'../src/plugins'))
import_fmt = '''import {{ plugin as p_{0} }}  from "./plugins/{0}/plugin"\n'''
for d in p.iterdir():
    p = d.name
    import_code = import_fmt.format(p)
    plugins.append(p)
    ctxt += import_code
print("plugins:", plugins)
ctxt += "\n\n"
ctxt += '''export const configPlugins = [ \n'''
for p in plugins:
    ctxt +="    p_" + p + ',\n'
ctxt += ''']'''

f = open(os.path.join(pwd,"../src/config.ts"), "w")
f.write(ctxt)
f.close()


