// generated by rollup compile script
// do not edit it
import { plugin as p_11111111111111111111111111111111 } from "./plugins/11111111111111111111111111111111/plugin";
import { plugin as p_TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA } from "./plugins/TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA/plugin";
export var configPlugins = [
    p_11111111111111111111111111111111,
    p_TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA,
];
