
// generated by  compile script
// do not edit it

import { plugin as p_TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA }  from "./plugins/TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA/plugin"
import { plugin as p_11111111111111111111111111111111 }  from "./plugins/11111111111111111111111111111111/plugin"
export const configPlugins = [ 
    TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
    11111111111111111111111111111111
]